[package]
name = "py2rs-cookbook"
version = "0.1.0"
authors = ["guaifish <guaifish@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defaultmap = "0.5.0"
maplit = "1.0.2"
